return {
	{spawn='zeta.script.obj.trigger'},	-- touch to perform events 
	{spawn='zeta.script.obj.door'},
	{spawn='zeta.script.obj.blaster'},
	{spawn='zeta.script.obj.missilelauncher'},
	{spawn='zeta.script.obj.grenadelauncher'},
	{spawn='zeta.script.obj.item'},
	{spawn='zeta.script.obj.keycard'},
	{spawn='zeta.script.obj.heart'},
	{spawn='zeta.script.obj.attackbonus'},
	{spawn='zeta.script.obj.defensebonus'},
	{spawn='zeta.script.obj.energytank'},
	{spawn='zeta.script.obj.grenadeitem'},
	{spawn='zeta.script.obj.plasmarifle'},
	{spawn='zeta.script.obj.geemer'},
	{spawn='zeta.script.obj.redgeemer'},
	{spawn='zeta.script.obj.boss-geemer'},
	{spawn='zeta.script.obj.turret'},
	{spawn='zeta.script.obj.gato'},
	{spawn='zeta.script.obj.terminal'},
}
