{
	{pos={120.5,238},spawn="base.script.obj.start"},
	{pos={113.5,236},spawn="zeta.script.obj.terminal",text="evacuation orders given!\nplease proceed to launchpad 1 for immediate departure"},
	{pos={141.5,221},spawn="zeta.script.obj.terminal",text="team 1 left without us.\nteam 2's rocket won't start.\nI think I'm going to go activate the defense robot to help us fight these creatures off...",use="if object.hasGiven then return end\nobject.hasGiven = true\ncreate\n 'zeta.script.obj.item'\n {pos = object.pos + {-1,1},\n  sprite = 'keycard'}"},
	{pos={116.5,236},spawn="zeta.script.obj.terminal",text="defense protocols initiated\nweapons storage unlocked",use="if object.hasGiven then return end\nobject.hasGiven = true\ncreate\n 'zeta.script.obj.blaster'\n {pos=object.pos+{1,3}}\ncreate\n 'zeta.script.obj.grenadeitem'\n {pos=object.pos+{2,3}}\ncreate\n 'zeta.script.obj.grenadeitem'\n {pos=object.pos+{3,3}}"},
	{pos={10.5,206},spawn="zeta.script.obj.turret"},
	{pos={23.5,206},spawn="zeta.script.obj.turret"},
	{pos={6.5,199},spawn="zeta.script.obj.turret"},
	{pos={23.5,199},spawn="zeta.script.obj.turret"},
	{pos={27.5,199},spawn="zeta.script.obj.turret"},
	{pos={41.5,199},spawn="zeta.script.obj.turret"},
	{pos={22.5,161},spawn="zeta.script.obj.turret"},
	{pos={28.5,161},spawn="zeta.script.obj.turret"},
	{pos={28.5,159},spawn="zeta.script.obj.turret"},
	{pos={22.5,159},spawn="zeta.script.obj.turret"},
	{pos={11.5,159},spawn="zeta.script.obj.terminal",text="Emergency alarm deactivated\nDefense systems disabled",use="require'zeta.script.obj.turret'.deactivated = true"},
	{pos={28.5,129},spawn="zeta.script.obj.terminal",text="Journal Entry:\nWhen mining in the crust of this planet we stumbled across a unique cave system.\nNot sure how they were formed.\nThe minerals seem to proceed through the caves.\nThe prospecting company is eager for us to follow."},
	{pos={122.5,237},spawn="zeta.script.obj.heart"},
	{pos={110.5,236},spawn="zeta.script.obj.terminal",text="proceed west to find the entrance to the caves"},
	{pos={123.5,237},spawn="zeta.script.obj.heart"},
}