return {
	'coin.wav',
	'die.wav',
	'door.wav',
	'egghatch.wav',
	'fireball.wav',
	'hit.wav',
	'jump.wav',
	'kick.wav',
	'mushroom.wav',
	'spinjump-stomp.wav',
	'spinjump.wav',
	'springboard.wav',
	'sprout.wav',
	'stomp.wav',
	'swim.wav',
	'thwomp.wav',
}